version: '3'
services:
  app1:
    build: ./app1
    ports:
    - "5001:80"
  app2:
    build: ./app2
    ports:
    - "5002:80"
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - app1
      - app2
